import { setStorage, getStorage } from './storage';
import { v4 as uuidv4 } from 'uuid';
import CryptoJS from 'crypto-js';

 const mockFlights = [
  // Pune → Mumbai (4 flights)
  {
    id: '1',
    from: 'Pune',
    to: 'Mumbai',
    price: 4800,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '07:30',
    arrivalTime: '08:40',
    duration: '1h 10m',
    aircraft: 'A320',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '2',
    from: 'Pune',
    to: 'Mumbai',
    price: 5200,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '10:00',
    arrivalTime: '11:15',
    duration: '1h 15m',
    aircraft: 'A321',
    seatsAvailable: 55,
    seatsBooked: 10,
    timeSlot: 'morning',
  },
  {
    id: '3',
    from: 'Pune',
    to: 'Mumbai',
    price: 6000,
    airline: 'Vistara',
    stops: 0,
    departureTime: '14:30',
    arrivalTime: '15:45',
    duration: '1h 15m',
    aircraft: 'A320neo',
    seatsAvailable: 50,
    seatsBooked: 12,
    timeSlot: 'afternoon',
  },
  {
    id: '4',
    from: 'Pune',
    to: 'Mumbai',
    price: 4500,
    airline: 'AirAsia',
    stops: 0,
    departureTime: '20:15',
    arrivalTime: '21:30',
    duration: '1h 15m',
    aircraft: 'A320',
    seatsAvailable: 70,
    seatsBooked: 20,
    timeSlot: 'night',
  },

  // Pune → Delhi (4 flights)
  {
    id: '5',
    from: 'Pune',
    to: 'Delhi',
    price: 7000,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '06:45',
    arrivalTime: '09:00',
    duration: '2h 15m',
    aircraft: 'A321',
    seatsAvailable: 65,
    seatsBooked: 18,
    timeSlot: 'morning',
  },
  {
    id: '6',
    from: 'Pune',
    to: 'Delhi',
    price: 8200,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '09:15',
    arrivalTime: '12:00',
    duration: '2h 45m',
    aircraft: 'A320',
    seatsAvailable: 50,
    seatsBooked: 10,
    timeSlot: 'morning',
  },
  {
    id: '7',
    from: 'Pune',
    to: 'Delhi',
    price: 9000,
    airline: 'AirIndia',
    stops: 1,
    departureTime: '17:00',
    arrivalTime: '20:15',
    duration: '3h 15m',
    aircraft: 'A319',
    seatsAvailable: 45,
    seatsBooked: 8,
    timeSlot: 'evening',
  },
  {
    id: '8',
    from: 'Pune',
    to: 'Delhi',
    price: 7500,
    airline: 'SpiceJet',
    stops: 1,
    departureTime: '13:30',
    arrivalTime: '16:30',
    duration: '3h 00m',
    aircraft: 'B737',
    seatsAvailable: 55,
    seatsBooked: 15,
    timeSlot: 'afternoon',
  },

  // Pune → Bangalore (4 flights)
  {
    id: '9',
    from: 'Pune',
    to: 'Bangalore',
    price: 6200,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '08:00',
    arrivalTime: '09:30',
    duration: '1h 30m',
    aircraft: 'A320',
    seatsAvailable: 60,
    seatsBooked: 12,
    timeSlot: 'morning',
  },
  {
    id: '10',
    from: 'Pune',
    to: 'Bangalore',
    price: 6800,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '11:00',
    arrivalTime: '12:30',
    duration: '1h 30m',
    aircraft: 'A321',
    seatsAvailable: 50,
    seatsBooked: 10,
    timeSlot: 'morning',
  },
  {
    id: '11',
    from: 'Pune',
    to: 'Bangalore',
    price: 7400,
    airline: 'Vistara',
    stops: 0,
    departureTime: '18:30',
    arrivalTime: '20:00',
    duration: '1h 30m',
    aircraft: 'A320neo',
    seatsAvailable: 40,
    seatsBooked: 5,
    timeSlot: 'evening',
  },
  {
    id: '12',
    from: 'Pune',
    to: 'Bangalore',
    price: 8000,
    airline: 'Akasa Air',
    stops: 1,
    departureTime: '15:00',
    arrivalTime: '18:00',
    duration: '3h 00m',
    aircraft: 'B737 MAX',
    seatsAvailable: 50,
    seatsBooked: 8,
    timeSlot: 'afternoon',
  },

  // Pune → Chennai (4 flights)
  {
    id: '13',
    from: 'Pune',
    to: 'Chennai',
    price: 7500,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '07:15',
    arrivalTime: '10:15',
    duration: '3h 00m',
    aircraft: 'A320',
    seatsAvailable: 55,
    seatsBooked: 12,
    timeSlot: 'morning',
  },
  {
    id: '14',
    from: 'Pune',
    to: 'Chennai',
    price: 8200,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '10:30',
    arrivalTime: '13:45',
    duration: '3h 15m',
    aircraft: 'A321',
    seatsAvailable: 50,
    seatsBooked: 10,
    timeSlot: 'morning',
  },
  {
    id: '15',
    from: 'Pune',
    to: 'Chennai',
    price: 9000,
    airline: 'AirIndia',
    stops: 2,
    departureTime: '14:00',
    arrivalTime: '18:45',
    duration: '4h 45m',
    aircraft: 'A319',
    seatsAvailable: 40,
    seatsBooked: 8,
    timeSlot: 'afternoon',
  },
  {
    id: '16',
    from: 'Pune',
    to: 'Chennai',
    price: 7800,
    airline: 'SpiceJet',
    stops: 1,
    departureTime: '19:00',
    arrivalTime: '22:15',
    duration: '3h 15m',
    aircraft: 'B737',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'evening',
  },

  // Mumbai → Pune (4 flights)
  {
    id: '17',
    from: 'Mumbai',
    to: 'Pune',
    price: 4900,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '06:30',
    arrivalTime: '07:45',
    duration: '1h 15m',
    aircraft: 'A320',
    seatsAvailable: 70,
    seatsBooked: 20,
    timeSlot: 'morning',
  },
  {
    id: '18',
    from: 'Mumbai',
    to: 'Pune',
    price: 5300,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '09:00',
    arrivalTime: '10:15',
    duration: '1h 15m',
    aircraft: 'A321',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '19',
    from: 'Mumbai',
    to: 'Pune',
    price: 5800,
    airline: 'AirAsia',
    stops: 0,
    departureTime: '12:30',
    arrivalTime: '13:45',
    duration: '1h 15m',
    aircraft: 'A320',
    seatsAvailable: 65,
    seatsBooked: 18,
    timeSlot: 'afternoon',
  },
  {
    id: '20',
    from: 'Mumbai',
    to: 'Pune',
    price: 6200,
    airline: 'Vistara',
    stops: 0,
    departureTime: '21:00',
    arrivalTime: '22:15',
    duration: '1h 15m',
    aircraft: 'A320neo',
    seatsAvailable: 50,
    seatsBooked: 10,
    timeSlot: 'night',
  },

  // Mumbai → Delhi (4 flights)
  {
    id: '21',
    from: 'Mumbai',
    to: 'Delhi',
    price: 6500,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '07:00',
    arrivalTime: '09:15',
    duration: '2h 15m',
    aircraft: 'A321',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '22',
    from: 'Mumbai',
    to: 'Delhi',
    price: 7200,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '10:15',
    arrivalTime: '13:00',
    duration: '2h 45m',
    aircraft: 'A320',
    seatsAvailable: 55,
    seatsBooked: 12,
    timeSlot: 'morning',
  },
  {
    id: '23',
    from: 'Mumbai',
    to: 'Delhi',
    price: 8500,
    airline: 'AirIndia',
    stops: 0,
    departureTime: '18:00',
    arrivalTime: '20:15',
    duration: '2h 15m',
    aircraft: 'A321',
    seatsAvailable: 50,
    seatsBooked: 10,
    timeSlot: 'evening',
  },
  {
    id: '24',
    from: 'Mumbai',
    to: 'Delhi',
    price: 7800,
    airline: 'SpiceJet',
    stops: 1,
    departureTime: '14:45',
    arrivalTime: '17:45',
    duration: '3h 00m',
    aircraft: 'B737',
    seatsAvailable: 60,
    seatsBooked: 18,
    timeSlot: 'afternoon',
  },

  // Mumbai → Bangalore (4 flights)
  {
    id: '25',
    from: 'Mumbai',
    to: 'Bangalore',
    price: 5500,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '06:15',
    arrivalTime: '07:55',
    duration: '1h 40m',
    aircraft: 'A320',
    seatsAvailable: 65,
    seatsBooked: 20,
    timeSlot: 'morning',
  },
  {
    id: '26',
    from: 'Mumbai',
    to: 'Bangalore',
    price: 6200,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '09:30',
    arrivalTime: '11:10',
    duration: '1h 40m',
    aircraft: 'A321',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '27',
    from: 'Mumbai',
    to: 'Bangalore',
    price: 7000,
    airline: 'GoAir',
    stops: 0,
    departureTime: '20:30',
    arrivalTime: '22:10',
    duration: '1h 40m',
    aircraft: 'A320',
    seatsAvailable: 50,
    seatsBooked: 10,
    timeSlot: 'night',
  },
  {
    id: '28',
    from: 'Mumbai',
    to: 'Bangalore',
    price: 6500,
    airline: 'AirAsia',
    stops: 1,
    departureTime: '13:00',
    arrivalTime: '15:45',
    duration: '2h 45m',
    aircraft: 'A320',
    seatsAvailable: 55,
    seatsBooked: 12,
    timeSlot: 'afternoon',
  },

  // Mumbai → Chennai (4 flights)
  {
    id: '29',
    from: 'Mumbai',
    to: 'Chennai',
    price: 6800,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '08:30',
    arrivalTime: '11:15',
    duration: '2h 45m',
    aircraft: 'A320',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '30',
    from: 'Mumbai',
    to: 'Chennai',
    price: 7400,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '11:15',
    arrivalTime: '14:00',
    duration: '2h 45m',
    aircraft: 'A321',
    seatsAvailable: 55,
    seatsBooked: 10,
    timeSlot: 'morning',
  },
  {
    id: '31',
    from: 'Mumbai',
    to: 'Chennai',
    price: 8200,
    airline: 'Akasa Air',
    stops: 1,
    departureTime: '17:45',
    arrivalTime: '20:45',
    duration: '3h 00m',
    aircraft: 'B737 MAX',
    seatsAvailable: 50,
    seatsBooked: 12,
    timeSlot: 'evening',
  },
  {
    id: '32',
    from: 'Mumbai',
    to: 'Chennai',
    price: 7000,
    airline: 'AirIndia',
    stops: 1,
    departureTime: '14:15',
    arrivalTime: '17:15',
    duration: '3h 00m',
    aircraft: 'A319',
    seatsAvailable: 60,
    seatsBooked: 18,
    timeSlot: 'afternoon',
  },

  // Delhi → Pune (4 flights)
  {
    id: '33',
    from: 'Delhi',
    to: 'Pune',
    price: 7100,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '06:00',
    arrivalTime: '08:15',
    duration: '2h 15m',
    aircraft: 'A321',
    seatsAvailable: 65,
    seatsBooked: 20,
    timeSlot: 'morning',
  },
  {
    id: '34',
    from: 'Delhi',
    to: 'Pune',
    price: 7800,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '09:45',
    arrivalTime: '12:30',
    duration: '2h 45m',
    aircraft: 'A320',
    seatsAvailable: 55,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '35',
    from: 'Delhi',
    to: 'Pune',
    price: 8500,
    airline: 'Vistara',
    stops: 1,
    departureTime: '15:30',
    arrivalTime: '18:30',
    duration: '3h 00m',
    aircraft: 'A320neo',
    seatsAvailable: 50,
    seatsBooked: 10,
    timeSlot: 'afternoon',
  },
  {
    id: '36',
    from: 'Delhi',
    to: 'Pune',
    price: 7300,
    airline: 'SpiceJet',
    stops: 1,
    departureTime: '19:15',
    arrivalTime: '22:00',
    duration: '2h 45m',
    aircraft: 'B737',
    seatsAvailable: 60,
    seatsBooked: 12,
    timeSlot: 'evening',
  },

  // Delhi → Mumbai (4 flights)
  {
    id: '37',
    from: 'Delhi',
    to: 'Mumbai',
    price: 6200,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '07:15',
    arrivalTime: '09:30',
    duration: '2h 15m',
    aircraft: 'A321',
    seatsAvailable: 70,
    seatsBooked: 25,
    timeSlot: 'morning',
  },
  {
    id: '38',
    from: 'Delhi',
    to: 'Mumbai',
    price: 6900,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '10:00',
    arrivalTime: '12:45',
    duration: '2h 45m',
    aircraft: 'A320',
    seatsAvailable: 60,
    seatsBooked: 20,
    timeSlot: 'morning',
  },
  {
    id: '39',
    from: 'Delhi',
    to: 'Mumbai',
    price: 7800,
    airline: 'AirIndia',
    stops: 0,
    departureTime: '18:30',
    arrivalTime: '20:45',
    duration: '2h 15m',
    aircraft: 'A321',
    seatsAvailable: 50,
    seatsBooked: 15,
    timeSlot: 'evening',
  },
  {
    id: '40',
    from: 'Delhi',
    to: 'Mumbai',
    price: 7200,
    airline: 'SpiceJet',
    stops: 1,
    departureTime: '13:15',
    arrivalTime: '16:15',
    duration: '3h 00m',
    aircraft: 'B737',
    seatsAvailable: 65,
    seatsBooked: 18,
    timeSlot: 'afternoon',
  },

  // Delhi → Bangalore (4 flights)
  {
    id: '41',
    from: 'Delhi',
    to: 'Bangalore',
    price: 8000,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '06:30',
    arrivalTime: '09:15',
    duration: '2h 45m',
    aircraft: 'A321',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '42',
    from: 'Delhi',
    to: 'Bangalore',
    price: 8700,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '09:00',
    arrivalTime: '11:45',
    duration: '2h 45m',
    aircraft: 'A320',
    seatsAvailable: 55,
    seatsBooked: 10,
    timeSlot: 'morning',
  },
  {
    id: '43',
    from: 'Delhi',
    to: 'Bangalore',
    price: 9500,
    airline: 'AirIndia',
    stops: 0,
    departureTime: '20:00',
    arrivalTime: '22:45',
    duration: '2h 45m',
    aircraft: 'A321',
    seatsAvailable: 45,
    seatsBooked: 12,
    timeSlot: 'night',
  },
  {
    id: '44',
    from: 'Delhi',
    to: 'Bangalore',
    price: 8200,
    airline: 'Vistara',
    stops: 1,
    departureTime: '14:30',
    arrivalTime: '17:45',
    duration: '3h 15m',
    aircraft: 'A320neo',
    seatsAvailable: 50,
    seatsBooked: 8,
    timeSlot: 'afternoon',
  },

  // Delhi → Chennai (4 flights)
  {
    id: '45',
    from: 'Delhi',
    to: 'Chennai',
    price: 8200,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '07:30',
    arrivalTime: '10:20',
    duration: '2h 50m',
    aircraft: 'A321',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '46',
    from: 'Delhi',
    to: 'Chennai',
    price: 8900,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '10:45',
    arrivalTime: '13:35',
    duration: '2h 50m',
    aircraft: 'A320',
    seatsAvailable: 55,
    seatsBooked: 12,
    timeSlot: 'morning',
  },
  {
    id: '47',
    from: 'Delhi',
    to: 'Chennai',
    price: 9700,
    airline: 'Vistara',
    stops: 0,
    departureTime: '17:30',
    arrivalTime: '20:20',
    duration: '2h 50m',
    aircraft: 'A320neo',
    seatsAvailable: 50,
    seatsBooked: 10,
    timeSlot: 'evening',
  },
  {
    id: '48',
    from: 'Delhi',
    to: 'Chennai',
    price: 8500,
    airline: 'AirIndia',
    stops: 1,
    departureTime: '13:00',
    arrivalTime: '16:15',
    duration: '3h 15m',
    aircraft: 'A319',
    seatsAvailable: 60,
    seatsBooked: 18,
    timeSlot: 'afternoon',
  },

  // Bangalore → Pune (4 flights)
  {
    id: '49',
    from: 'Bangalore',
    to: 'Pune',
    price: 6400,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '06:45',
    arrivalTime: '08:15',
    duration: '1h 30m',
    aircraft: 'A320',
    seatsAvailable: 65,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '50',
    from: 'Bangalore',
    to: 'Pune',
    price: 7000,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '09:15',
    arrivalTime: '11:45',
    duration: '2h 30m',
    aircraft: 'A321',
    seatsAvailable: 55,
    seatsBooked: 10,
    timeSlot: 'morning',
  },
  {
    id: '51',
    from: 'Bangalore',
    to: 'Pune',
    price: 7800,
    airline: 'Akasa Air',
    stops: 1,
    departureTime: '15:45',
    arrivalTime: '18:15',
    duration: '2h 30m',
    aircraft: 'B737 MAX',
    seatsAvailable: 50,
    seatsBooked: 8,
    timeSlot: 'afternoon',
  },
  {
    id: '52',
    from: 'Bangalore',
    to: 'Pune',
    price: 7200,
    airline: 'SpiceJet',
    stops: 1,
    departureTime: '19:00',
    arrivalTime: '21:30',
    duration: '2h 30m',
    aircraft: 'B737',
    seatsAvailable: 60,
    seatsBooked: 12,
    timeSlot: 'evening',
  },

  // Bangalore → Mumbai (4 flights)
  {
    id: '53',
    from: 'Bangalore',
    to: 'Mumbai',
    price: 5600,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '06:00',
    arrivalTime: '07:40',
    duration: '1h 40m',
    aircraft: 'A320',
    seatsAvailable: 70,
    seatsBooked: 20,
    timeSlot: 'morning',
  },
  {
    id: '54',
    from: 'Bangalore',
    to: 'Mumbai',
    price: 6200,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '09:30',
    arrivalTime: '11:10',
    duration: '1h 40m',
    aircraft: 'A321',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '55',
    from: 'Bangalore',
    to: 'Mumbai',
    price: 7000,
    airline: 'GoAir',
    stops: 0,
    departureTime: '18:15',
    arrivalTime: '19:55',
    duration: '1h 40m',
    aircraft: 'A320',
    seatsAvailable: 55,
    seatsBooked: 12,
    timeSlot: 'evening',
  },
  {
    id: '56',
    from: 'Bangalore',
    to: 'Mumbai',
    price: 6500,
    airline: 'SpiceJet',
    stops: 1,
    departureTime: '13:30',
    arrivalTime: '16:00',
    duration: '2h 30m',
    aircraft: 'B737',
    seatsAvailable: 60,
    seatsBooked: 18,
    timeSlot: 'afternoon',
  },

  // Bangalore → Delhi (4 flights)
  {
    id: '57',
    from: 'Bangalore',
    to: 'Delhi',
    price: 7800,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '07:00',
    arrivalTime: '09:45',
    duration: '2h 45m',
    aircraft: 'A321',
    seatsAvailable: 65,
    seatsBooked: 20,
    timeSlot: 'morning',
  },
  {
    id: '58',
    from: 'Bangalore',
    to: 'Delhi',
    price: 8500,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '10:15',
    arrivalTime: '13:00',
    duration: '2h 45m',
    aircraft: 'A320',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '59',
    from: 'Bangalore',
    to: 'Delhi',
    price: 9200,
    airline: 'Vistara',
    stops: 0,
    departureTime: '21:15',
    arrivalTime: '00:00',
    duration: '2h 45m',
    aircraft: 'A320neo',
    seatsAvailable: 50,
    seatsBooked: 10,
    timeSlot: 'night',
  },
  {
    id: '60',
    from: 'Bangalore',
    to: 'Delhi',
    price: 8200,
    airline: 'AirIndia',
    stops: 1,
    departureTime: '14:00',
    arrivalTime: '17:15',
    duration: '3h 15m',
    aircraft: 'A319',
    seatsAvailable: 55,
    seatsBooked: 12,
    timeSlot: 'afternoon',
  },

  // Bangalore → Chennai (4 flights)
  {
    id: '61',
    from: 'Bangalore',
    to: 'Chennai',
    price: 3200,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '06:30',
    arrivalTime: '07:30',
    duration: '1h 00m',
    aircraft: 'A320',
    seatsAvailable: 80,
    seatsBooked: 25,
    timeSlot: 'morning',
  },
  {
    id: '62',
    from: 'Bangalore',
    to: 'Chennai',
    price: 3500,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '09:00',
    arrivalTime: '10:00',
    duration: '1h 00m',
    aircraft: 'A321',
    seatsAvailable: 75,
    seatsBooked: 20,
    timeSlot: 'morning',
  },
  {
    id: '63',
    from: 'Bangalore',
    to: 'Chennai',
    price: 4000,
    airline: 'AirAsia',
    stops: 0,
    departureTime: '12:15',
    arrivalTime: '13:15',
    duration: '1h 00m',
    aircraft: 'A320',
    seatsAvailable: 70,
    seatsBooked: 15,
    timeSlot: 'afternoon',
  },
  {
    id: '64',
    from: 'Bangalore',
    to: 'Chennai',
    price: 3800,
    airline: 'SpiceJet',
    stops: 0,
    departureTime: '17:30',
    arrivalTime: '18:30',
    duration: '1h 00m',
    aircraft: 'B737',
    seatsAvailable: 65,
    seatsBooked: 18,
    timeSlot: 'evening',
  },

  // Chennai → Pune (4 flights)
  {
    id: '65',
    from: 'Chennai',
    to: 'Pune',
    price: 7600,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '06:15',
    arrivalTime: '09:30',
    duration: '3h 15m',
    aircraft: 'A320',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '66',
    from: 'Chennai',
    to: 'Pune',
    price: 8200,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '09:30',
    arrivalTime: '12:45',
    duration: '3h 15m',
    aircraft: 'A321',
    seatsAvailable: 55,
    seatsBooked: 12,
    timeSlot: 'morning',
  },
  {
    id: '67',
    from: 'Chennai',
    to: 'Pune',
    price: 9000,
    airline: 'AirIndia',
    stops: 1,
    departureTime: '14:45',
    arrivalTime: '18:00',
    duration: '3h 15m',
    aircraft: 'A319',
    seatsAvailable: 50,
    seatsBooked: 10,
    timeSlot: 'afternoon',
  },
  {
    id: '68',
    from: 'Chennai',
    to: 'Pune',
    price: 8500,
    airline: 'SpiceJet',
    stops: 2,
    departureTime: '17:15',
    arrivalTime: '22:00',
    duration: '4h 45m',
    aircraft: 'B737',
    seatsAvailable: 45,
    seatsBooked: 8,
    timeSlot: 'evening',
  },

  // Chennai → Mumbai (4 flights)
  {
    id: '69',
    from: 'Chennai',
    to: 'Mumbai',
    price: 7200,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '07:00',
    arrivalTime: '09:45',
    duration: '2h 45m',
    aircraft: 'A320',
    seatsAvailable: 65,
    seatsBooked: 20,
    timeSlot: 'morning',
  },
  {
    id: '70',
    from: 'Chennai',
    to: 'Mumbai',
    price: 7800,
    airline: 'IndiGo',
    stops: 1,
    departureTime: '10:15',
    arrivalTime: '13:00',
    duration: '2h 45m',
    aircraft: 'A321',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '71',
    from: 'Chennai',
    to: 'Mumbai',
    price: 8500,
    airline: 'SpiceJet',
    stops: 1,
    departureTime: '16:30',
    arrivalTime: '19:15',
    duration: '2h 45m',
    aircraft: 'B737',
    seatsAvailable: 55,
    seatsBooked: 12,
    timeSlot: 'evening',
  },
  {
    id: '72',
    from: 'Chennai',
    to: 'Mumbai',
    price: 8000,
    airline: 'AirIndia',
    stops: 1,
    departureTime: '13:00',
    arrivalTime: '15:45',
    duration: '2h 45m',
    aircraft: 'A319',
    seatsAvailable: 60,
    seatsBooked: 18,
    timeSlot: 'afternoon',
  },

  // Chennai → Delhi (4 flights)
  {
    id: '73',
    from: 'Chennai',
    to: 'Delhi',
    price: 8500,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '06:45',
    arrivalTime: '09:40',
    duration: '2h 55m',
    aircraft: 'A321',
    seatsAvailable: 60,
    seatsBooked: 15,
    timeSlot: 'morning',
  },
  {
    id: '74',
    from: 'Chennai',
    to: 'Delhi',
    price: 9200,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '09:15',
    arrivalTime: '12:10',
    duration: '2h 55m',
    aircraft: 'A320',
    seatsAvailable: 55,
    seatsBooked: 12,
    timeSlot: 'morning',
  },
  {
    id: '75',
    from: 'Chennai',
    to: 'Delhi',
    price: 9800,
    airline: 'Vistara',
    stops: 0,
    departureTime: '18:00',
    arrivalTime: '20:55',
    duration: '2h 55m',
    aircraft: 'A320neo',
    seatsAvailable: 50,
    seatsBooked: 10,
    timeSlot: 'evening',
  },
  {
    id: '76',
    from: 'Chennai',
    to: 'Delhi',
    price: 9000,
    airline: 'AirIndia',
    stops: 1,
    departureTime: '14:15',
    arrivalTime: '17:30',
    duration: '3h 15m',
    aircraft: 'A319',
    seatsAvailable: 60,
    seatsBooked: 18,
    timeSlot: 'afternoon',
  },

  // Chennai → Bangalore (4 flights)
  {
    id: '77',
    from: 'Chennai',
    to: 'Bangalore',
    price: 3100,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '06:15',
    arrivalTime: '07:15',
    duration: '1h 00m',
    aircraft: 'A320',
    seatsAvailable: 80,
    seatsBooked: 25,
    timeSlot: 'morning',
  },
  {
    id: '78',
    from: 'Chennai',
    to: 'Bangalore',
    price: 3400,
    airline: 'IndiGo',
    stops: 0,
    departureTime: '09:30',
    arrivalTime: '10:30',
    duration: '1h 00m',
    aircraft: 'A321',
    seatsAvailable: 75,
    seatsBooked: 20,
    timeSlot: 'morning',
  },
  {
    id: '79',
    from: 'Chennai',
    to: 'Bangalore',
    price: 3900,
    airline: 'AirAsia',
    stops: 0,
    departureTime: '12:30',
    arrivalTime: '13:30',
    duration: '1h 00m',
    aircraft: 'A320',
    seatsAvailable: 70,
    seatsBooked: 15,
    timeSlot: 'afternoon',
  },
  {
    id: '80',
    from: 'Chennai',
    to: 'Bangalore',
    price: 4500,
    airline: 'SpiceJet',
    stops: 0,
    departureTime: '17:15',
    arrivalTime: '18:15',
    duration: '1h 00m',
    aircraft: 'B737',
    seatsAvailable: 65,
    seatsBooked: 18,
    timeSlot: 'evening',
  },
];

const defaultUsers = [
  {
    id: uuidv4(),
    name: 'Admin User',
    email: 'admin@example.com',
    password: CryptoJS.AES.encrypt('admin123', 'secret-key').toString(),
    role: 'Admin',
  },
  {
    id: uuidv4(),
    name: 'Regular User',
    email: 'user@example.com',
    password: CryptoJS.AES.encrypt('user123', 'secret-key').toString(),
    role: 'User',
  },
];

const defaultBookings = [
  {
    id: uuidv4(),
    userId: defaultUsers[1].id,
    flightId: '1',
    passengers: [{ name: 'Regular User', age: 30 }],
    totalPrice: 4800,
    date: new Date().toISOString(),
    status: 'Confirmed',
  },
];

export const initializeStorage = () => {
  // Initialize flights
  if (!getStorage('flights')) {
    console.log('Initializing flights in localStorage');
    setStorage('flights', mockFlights);
  }

  // Initialize users
  if (!getStorage('users')) {
    console.log('Initializing users in localStorage');
    setStorage('users', defaultUsers);
  }

  // Initialize bookings
  if (!getStorage('bookings')) {
    console.log('Initializing bookings in localStorage');
    setStorage('bookings', defaultBookings);
  }
};